#!/usr/bin/env php
<?php
/**
 * Worklog application bootstrap
 *
 * @author      Allen McCabe
 */

/*
 * Bootstrap the application
 */
define('MINIMUM_PHP_VERSION', '5.5.0');
define('APPLICATION_PATH', getcwd());
define('CACHE_DIRECTORY', '/scripts/worklog/cache');
define('DEVELOPMENT_MODE', false);
define('DEFAULT_COMMAND', 'today');
include(__DIR__.'/src/bootstrap.php');

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

/*********************************************/
// Bind commands
/*********************************************/

use CSATF\CommandLine\Command;
use CSATF\Database\Drivers\RedisDatabaseDriver;

$db = new RedisDatabaseDriver([
    'database' => (int) getenv('REDIS_DATABASE_INDEX'),
    'prefix' => basename(__FILE__).':',
    'schema_path' => getenv('REDIS_DATABASE_SCHEMA_PATH') || '/usr/share/redisdb/redis-0.json',
    'path' => getenv('REDIS_DATABASE_SCHEMA_PATH') || APPLICATION_PATH
]);

//$data = [];
//$keys = App()->db()->keys('*');
//foreach ($keys as $_key => $key) {
////    $data[$key] = App()->db()->get($key);
//    $id = preg_replace('/[^0-9]/', '', $key);
//    $rec = App()->db()->get($key);
//
//    foreach ($rec as $_pk => $item) {
//
//        if ($item->id == 21) {
//            dump($item);
////            dump($key);
////            print "\n";
////            dump($id);
////            print "\n";
////            die ($id.' != '.$item->id);
//        }
//    }
//}
//dump($data);

Command::bind('help', 'Worklog\CommandLine\UsageCommand');
Command::bind('add', 'Worklog\CommandLine\WriteCommand');
Command::bind('list', 'Worklog\CommandLine\ListCommand');
Command::bind('detail', 'Worklog\CommandLine\DetailCommand');
Command::bind('edit', 'Worklog\CommandLine\EditCommand');
Command::bind('delete', 'Worklog\CommandLine\DeleteCommand');
Command::bind('report', 'Worklog\CommandLine\ReportCommand');
Command::bind('today', 'Worklog\CommandLine\TodayCommand');
Command::bind('start', 'Worklog\CommandLine\StartCommand');
Command::bind('stop', 'Worklog\CommandLine\StopCommand');

include(__DIR__.'/src/run.php');