#!/usr/bin/env php
<?php
/**
 * Worklog application bootstrap
 *
 * @author      Allen McCabe
 */

/*
 * Bootstrap the application
 */
define('MINIMUM_PHP_VERSION', '5.5.0');
define('APPLICATION_PATH', __DIR__);
define('CACHE_DIRECTORY', '/scripts/worklog/cache');
define('DATABASE_PATH', APPLICATION_PATH.'/database');
define('DATABASE_MIGRATIONS', DATABASE_PATH.'/migrations');
define('DEVELOPMENT_MODE', false);
define('DEFAULT_COMMAND', 'today');
include(__DIR__.'/src/bootstrap.php');

use CSATF\CommandLine\Command;

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();


$db = database(getenv('DATABASE_DRIVER'));


/*********************************************/
// Bind commands
/*********************************************/

Command::bind('migrate', 'CSATF\CommandLine\MigrateCommand');
Command::bind('migrate:rollback', 'CSATF\CommandLine\MigrateRollbackCommand');
Command::bind('migrate:status', 'CSATF\CommandLine\MigrationStatusCommand');
Command::bind('make:migration', 'CSATF\CommandLine\CreateMigrationCommand');

Command::bind('help', 'Worklog\CommandLine\UsageCommand');
Command::bind('add', 'Worklog\CommandLine\WriteCommand');
Command::bind('list', 'Worklog\CommandLine\ListCommand');
Command::bind('detail', 'Worklog\CommandLine\DetailCommand');
Command::bind('edit', 'Worklog\CommandLine\EditCommand');
Command::bind('delete', 'Worklog\CommandLine\DeleteCommand');
Command::bind('report', 'Worklog\CommandLine\ReportCommand');
Command::bind('today', 'Worklog\CommandLine\TodayCommand');
Command::bind('start', 'Worklog\CommandLine\StartCommand');
Command::bind('stop', 'Worklog\CommandLine\StopCommand');
Command::bind('recover', 'Worklog\CommandLine\RecoverCommand');
Command::bind('cancel', 'Worklog\CommandLine\CancelCommand');


include(__DIR__.'/src/run.php');